version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/app
      - storage:/var/www/app/storage
      - laravel_cache:/var/www/app/bootstrap/cache
      - entrypoint:/var/www/app/webserver
    env_file:
      - .env
    ports:
      - "8082:80"
      - "5173:5173"
    networks:
      - localhost
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - localhost
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'exatait'
      MYSQL_USER: 'exatait'
      MYSQL_PASSWORD: 'exatait'
      MYSQL_ROOT_PASSWORD: 'exatait'
    ports:
      - "3306:3306"
    volumes:
     - mysql_data:/var/lib/mysql
    networks:
      - localhost

volumes:
  storage:
  laravel_cache:
  entrypoint:
  mysql_data:

networks:
  localhost:
    driver: bridge
